body: The side body element helps to create block having side columns.
page_title: 'Side body'
title:
  horizontal:
    left: Left column
    right: Right column
    both: Double columns
  vertical:
    top: Header
    bottom: Footer
    both: Header and footer