parameters:
    wexample_symfony_design_system.loader.layout_bases:
        modal:
            page_manager_component: '@@WexampleSymfonyDesignSystemBundle/components/modal'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyDesignSystem\Controller\:
        resource: '../../Controller/'
        exclude: '../../Controller/**/Abstract*.php'

    Wexample\SymfonyDesignSystem\Twig\:
        resource: '../../Twig/'
