page_title: Cards

section:
  three_cards: Three cards
  two_cards: Two cards

card:
  one:
    title: Card Title
    content:
      This card contains a detailed explanation designed to provide users with helpful, relevant information. Whether you're browsing for inspiration, looking for practical guidance, or simply trying to better understand the context of a topic, this content aims to deliver value clearly and concisely.
      The text displayed here is meant to demonstrate how longer blocks of content will appear when rendered within the card layout. It’s important to ensure that even with multiple paragraphs, the overall design remains readable, aesthetically balanced, and responsive on all screen sizes.
    button: Action
  two:
    title: Card with Image
    image_alt: Example image
    content: Card with an image and text.
    button: See more
  three:
    title: Simple Card
    content: Minimalist version with content only.