page_title: Cards

section:
  three_cards: Trois cartes
  two_cards: Deux cartes

card:
  one:
    title: Titre de la carte
    content: Contenu de la carte avec du texte standard. Ceci est un exemple de contenu.
    button: Action
  two:
    title: Carte avec image
    image_alt: Image d'exemple
    content: Carte avec une image et du texte.
    button: Voir plus
  three:
    title: Carte simple
    content: Version minimaliste avec seulement du contenu.
