page_title: Cards

section:
  basic: Basic Cards

card:
  one:
    title: Card Title
    content: Card content with standard text. This is an example content.
    button: Action
  two:
    title: Card with Image
    image_alt: Example image
    content: Card with an image and text.
    button: See more
  three:
    title: Simple Card
    content: Minimalist version with content only.